config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  root 'homes#top'
  get '/' => 'homes#top'
  get 'home/about' => 'homes#about', as: :about_homes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :homes, dependent: :destroy
  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true,  length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
before_action :configure_permitted_parameters, if: :devise_controller?
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
	# before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@newbook = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@newbook = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
      else
        render "edit"
      end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   # def baria_user
  	# unless params[:id].to_i == current_user.id
  	# 	redirect_to user_path(current_user)
  	# end
   # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="row">
	<%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
<table class="table">
		<tr></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>
</div>
<div class="row">
					<% if user == current_user %>
					<p>
						<%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% else %>
					<p>
						<%= link_to '', user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% end %>
				</div>

app/views/users/edit.html.erb
<div class="body">
	<div class="container">

<h2>User info</h2>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->
<%= form_for(@user) do |f| %>
				<div class="field">
					<label for="user_name">Name</label>
					<%= f.text_field :name %>
				</div>
				<div class="field">
					<label for="user_image">Image</label>
					<label class="control-label sr-only" for="inputEmail">ProfileImage</label>
	    			<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
	    		</div>
	    		<div class="field">
	    			<label for="user_introduction">Introduction</label>
	    			<%= f.text_area :introduction %>
	    		</div>
	    		<div class="actions">
	    			<%= f.submit "Update User" %>
	    		</div>
	    		<% end %>

</div>
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>

<h2>User info</h2>
<%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
<table class="table">
	<tbody>
		<tr></tr>

		<tr>
			<th>name</th>
			<th><%= current_user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= current_user.introduction %></th>
		</tr>
	</tbody>
</table>

<div class="row">
					<% if current_user == current_user %>
					<p>
						<%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% else %>
					<p>
						<%= link_to '', user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% end %>
				</div>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @newbook %>

</div>
<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %></td>
			<td><%= user.name%></td>
			<td><%= link_to "Show", user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
</div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>

<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
<table class="table">
	<tbody>
		<tr></tr>

		<tr>
			<th>name</th>
			<th><%= @user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @user.introduction %></th>
		</tr>
	</tbody>
</table>
<div class="row">
					<% if @user == current_user %>
					<p>
						<%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% else %>
					<p>
						<%= link_to '', user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% end %>
				</div>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @newbook %>

</div>
<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
				<% end %>
			</td>
			<td><%= link_to book.title, book_path(book.id) %></td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->

</div>
</div>
</div>
</div>