config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  root 'homes#top'
  get '/' => 'homes#top'
  get 'home/about' => 'homes#about', as: :about_homes
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!

  def show
  	@book = Book.find(params[:id])
    @newbook = Book.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @newbook = Book.new
  end

  def create
  	@newbook = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @newbook.user_id = current_user.id
  	if @newbook.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@newbook.id)
      else
        @books = Book.all
        render "index"
      end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    @book.user_id =current_user.id
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
      @books = Book.all
      if @book.destroy
        flash[:notice] = "Book was successfully destroyed."
        redirect_to books_path
      else
        render "index"
      end
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<div class="row">
</div>

<%= form_for(book) do |f| %>
	<div class="field row">
		<label for="book_title">title</label>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<label for="book_opinion">opinion</label><!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="body">
	<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>

				<% if @book.errors.any? %>
				<div >
					<h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
					<ul>
						<% @book.errors.full_messages.each do |m| %>
						<li><%= m %></li>
						<% end %>
					</ul>
				</div>
				<% end %>
				<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
					<div class="field row">
						<label for="book_title">Title</label>
					<%= f.text_field :title %>
					</div>
					<div class="field row">
					<label for="book_opinion">Opinion</label>
					<%= f.text_area :body %>
					</div>
					<div class="actions row">
						<%= f.submit "Update Book" %>
					</div>
					<% end %>


<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>
</div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>
<% if @newbook.errors.any? %>
<div class="col-xs-12" id="error_explanation">
	<h2>
		<%= @newbook.errors.count %> errors prohibited this book from being saved:</h2>
	<ul>
		<% @newbook.errors.full_messages.each do |m| %>
		<li><%= m %></li>
		<% end %>
	</ul>
</div>
<% end %><div class="body">
	<div class="container">

		<div class="row">
			<div class="col-xs-3">

		<h2>User info</h2>
		<%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
<table class="table">
	<tbody>
		<tr></tr>

		<tr>
			<th>name</th>
			<th><%= current_user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= current_user.introduction %></th>
		</tr>
	</tbody>
</table>

<div class="row">
					<% if current_user == current_user %>
					<p>
						<%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% else %>
					<p>
						<%= link_to '', user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% end %>
				</div>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user_id) do %>
								<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" , size: "10*10" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->
</div>
</div>

	</div>
</div>

app/views/books/show.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<% if flash[:notice] %>
					<div class="flash">
						<%= flash[:notice] %>
					</div>
				<% end %>

		<h2>User info</h2>
		<%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %>
<table class="table">
	<tbody>
		<tr></tr>

		<tr>
			<th>name</th>
			<th><%= @book.user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= @book.user.introduction %></th>
		</tr>
	</tbody>
</table>
				<div class="row">
					<% if @book.user == current_user %>
					<p>
						<%= link_to '', edit_user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% else %>
					<p>
						<%= link_to '', user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
					</p>
					<% end %>
				</div>

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "10*10" %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path %></td>
					<td><%= @book.body %></td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit",edit_book_path, class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<% end %>
					<% if @book.user == current_user %>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

	</div>
</div>
</div>
</div>